import dressOne from "../imgs/1.png";
import dressTwoAlt from "../imgs/2.jpg";
import dressTwo from "../imgs/3.jpg";
import dressThree from "../imgs/4.jpg";
import dressFour from "../imgs/indian.jpg";
import dressFive from "../imgs/7.jpg";
import dressSix from "../imgs/6.jpg";
import dressSeven from "../imgs/5.webp";
import cnyOne from "../imgs/cny 1.jfif";
import cnyTwo from "../imgs/cny 2.jfif";
import indianSaree from "../imgs/indian saree.jfif";
import mainInTwo from "../imgs/main in 2.png";
import mainInCnyOne from "../imgs/main in cny1.jpg";
import mainInCnyTwo from "../imgs/main in cny2.jpg";
import mainInIndianSaree from "../imgs/main in indian saree.jpg";
import mainInCnyTwoVideo from "../imgs/vids/main in cny2.mp4";
import mainInIndianSareeVideo from "../imgs/vids/Realistic_Dress_Walking_Video_Generated.mp4";

export const homeOutfits = [
  {
    id: "gallery-dinner-set",
    title: "Gallery Dinner Set",
    note: "Muted blush tailoring with silk camisole.",
    meta: "Tonight | AI confidence 96%",
    palette: ["#e8d5ce", "#d8b3ad", "#af8b83"],
    image: dressFive,
  },
  {
    id: "sunday-market-layer",
    title: "Sunday Market Layer",
    note: "Soft cupro shirt and cropped oatmeal trouser.",
    meta: "Weekend | Fabric-safe match",
    palette: ["#f1e7de", "#d6c0af", "#978276"],
    image: dressSix,
  },
  {
    id: "studio-work-uniform",
    title: "Studio Work Uniform",
    note: "Warm grey knit over cream column skirt.",
    meta: "Tomorrow | Shared nearby",
    palette: ["#ece4de", "#cfc2bd", "#8d827d"],
    image: dressSeven,
  },
];

export const sharedLooks = [
  {
    id: "blush-trench",
    title: "Blush trench",
    price: "$18/day",
    palette: ["#f0dfd8", "#d6b6aa", "#9f7a73"],
    image: dressTwo,
  },
  {
    id: "bone-coord",
    title: "Bone co-ord",
    price: "$24/day",
    palette: ["#f1ebe5", "#ddd1c7", "#b6a59b"],
    image: dressThree,
  },
  {
    id: "pearl-slip",
    title: "Pearl slip",
    price: "$20/day",
    palette: ["#f5ede9", "#dec4bb", "#ad8b84"],
    image: dressFour,
  },
  {
    id: "taupe-blazer",
    title: "Taupe blazer",
    price: "$22/day",
    palette: ["#ece1d5", "#cbb09a", "#8a7163"],
    image: dressSeven,
  },
];

export const marketItems = [
  {
    id: "ivory-eyelet-peplum",
    title: "Ivory eyelet peplum",
    dailyPrice: 20,
    fabric: "cotton",
    sensitive: true,
    occasion: false,
    occasionType: "daily-wear",
    ethnicStyle: "",
    condition: "brand-new",
    fit: "Peplum top",
    description: "Soft cotton eyelet peplum top with flutter sleeves and a clean square neckline.",
    palette: ["#f7efe8", "#e4d3c6", "#baa89d"],
    image: dressTwoAlt,
    preGeneratedTryOnImage: mainInTwo,
    category: "Tops",
    size: "S",
    sizeCategory: "S",
    sleeveLength: "short",
    dressLength: "mini",
    material: "cotton",
    garmentMeasurements: { bust: 86, waist: 70, hips: 94, length: 68 },
    owner: "Clara",
  },
  {
    id: "powder-drape-set",
    title: "Powder drape set",
    dailyPrice: 38,
    fabric: "silk",
    sensitive: true,
    occasion: true,
    occasionType: "formal",
    ethnicStyle: "",
    condition: "brand-new",
    fit: "Relaxed tailored",
    description: "Breathable cupro-silk blend with a fluid drape and soft inner finish.",
    palette: ["#f4e8e0", "#ddc2b8", "#bc9a90"],
    image: dressOne,
    category: "Dresses",
    size: "S-M",
    sizeCategory: "S",
    sleeveLength: "sleeveless",
    dressLength: "midi",
    material: "silk",
    garmentMeasurements: { bust: 86, waist: 68, hips: 94, length: 124 },
    owner: "Lina",
  },
  {
    id: "soft-cupro-suit",
    title: "Soft cupro suit",
    dailyPrice: 34,
    fabric: "cupro",
    sensitive: true,
    occasion: true,
    occasionType: "formal",
    ethnicStyle: "",
    condition: "worn-few",
    fit: "Reception",
    description: "Fluid suiting set designed for long events and camera-ready structure.",
    palette: ["#eee1d5", "#d6bba7", "#9d7c6b"],
    image: dressFive,
    category: "Sets",
    size: "M",
    sizeCategory: "M",
    sleeveLength: "long",
    dressLength: "midi",
    material: "cupro",
    garmentMeasurements: { bust: 92, waist: 74, hips: 100, length: 126 },
    owner: "Ari",
  },
  {
    id: "linen-day-set",
    title: "Linen day set",
    dailyPrice: 18,
    fabric: "linen",
    sensitive: false,
    occasion: false,
    occasionType: "daily-wear",
    ethnicStyle: "",
    condition: "worn-few",
    fit: "Day edit",
    description: "Easy warm-weather layer with breathable weave and relaxed fall.",
    palette: ["#f4ede5", "#d9cbbd", "#998b7d"],
    image: dressSix,
    category: "Separates",
    size: "S",
    sizeCategory: "S",
    sleeveLength: "short",
    dressLength: "mini",
    material: "linen",
    garmentMeasurements: { bust: 88, waist: 70, hips: 96, length: 92 },
    owner: "Mika",
  },
  {
    id: "silk-scarf-top",
    title: "Silk scarf top",
    dailyPrice: 16,
    fabric: "silk",
    sensitive: false,
    occasion: true,
    occasionType: "party",
    ethnicStyle: "",
    condition: "well-used",
    fit: "Dinner",
    description: "Evening top with soft tie detail and gentle sheen under low light.",
    palette: ["#f3dfda", "#d9b2af", "#a27d78"],
    image: dressFour,
    category: "Tops",
    size: "XS-S",
    sizeCategory: "XS",
    sleeveLength: "sleeveless",
    dressLength: "mini",
    material: "silk",
    garmentMeasurements: { bust: 82, waist: 66, hips: 90, length: 78 },
    owner: "June",
  },
  {
    id: "ivory-column-gown",
    title: "Ivory column gown",
    dailyPrice: 40,
    fabric: "satin",
    sensitive: true,
    occasion: true,
    occasionType: "formal",
    ethnicStyle: "",
    condition: "brand-new",
    fit: "Evening formal",
    description: "Long satin silhouette with a clean editorial line and soft underlayer.",
    palette: ["#f7efe7", "#e3d1c4", "#bca091"],
    image: dressSeven,
    category: "Dresses",
    size: "S",
    sizeCategory: "S",
    sleeveLength: "sleeveless",
    dressLength: "maxi",
    material: "satin",
    garmentMeasurements: { bust: 84, waist: 66, hips: 92, length: 142 },
    owner: "Noa",
  },
  {
    id: "blush-wrap-dress",
    title: "Blush wrap dress",
    dailyPrice: 22,
    fabric: "cotton",
    sensitive: true,
    occasion: false,
    occasionType: "daily-wear",
    ethnicStyle: "",
    condition: "worn-few",
    fit: "Brunch",
    description: "Easy wrap silhouette with a featherlight feel and soft movement.",
    palette: ["#f6e9e2", "#ddc0bb", "#bf9891"],
    image: dressTwo,
    category: "Dresses",
    size: "M-L",
    sizeCategory: "M",
    sleeveLength: "short",
    dressLength: "midi",
    material: "cotton",
    garmentMeasurements: { bust: 94, waist: 78, hips: 104, length: 118 },
    owner: "Eden",
  },
  {
    id: "cocoa-evening-slip",
    title: "Cocoa evening slip",
    dailyPrice: 30,
    fabric: "silk",
    sensitive: false,
    occasion: true,
    occasionType: "party",
    ethnicStyle: "",
    condition: "brand-new",
    fit: "Dinner",
    description: "Bias-cut slip dress with a subtle sheen and clean shoulder line.",
    palette: ["#f0e0d8", "#cfaa9c", "#8e6c60"],
    image: dressThree,
    category: "Dresses",
    size: "S-M",
    sizeCategory: "S",
    sleeveLength: "sleeveless",
    dressLength: "maxi",
    material: "silk",
    garmentMeasurements: { bust: 88, waist: 70, hips: 96, length: 138 },
    owner: "Sana",
  },
  {
    id: "pearl-structured-mini",
    title: "Pearl structured mini",
    dailyPrice: 27,
    fabric: "linen",
    sensitive: false,
    occasion: true,
    occasionType: "party",
    ethnicStyle: "",
    condition: "well-used",
    fit: "Cocktail",
    description: "Structured short dress with a sculpted bodice and crisp hem.",
    palette: ["#f5ece5", "#dac7ba", "#9e8b80"],
    image: dressFive,
    category: "Dresses",
    size: "XS",
    sizeCategory: "XS",
    sleeveLength: "short",
    dressLength: "mini",
    material: "linen",
    garmentMeasurements: { bust: 80, waist: 64, hips: 88, length: 86 },
    owner: "Tara",
  },
  {
    id: "jade-brocade-set",
    title: "Crimson qipao",
    dailyPrice: 35,
    fabric: "brocade",
    sensitive: false,
    occasion: true,
    occasionType: "ethnic",
    ethnicStyle: "chinese",
    condition: "brand-new",
    fit: "Traditional fitted",
    description: "Structured Chinese festive dress with a fitted silhouette and brocade finish.",
    palette: ["#e8ddd4", "#bca497", "#8a6e62"],
    image: cnyOne,
    preGeneratedTryOnImage: mainInCnyOne,
    category: "Ethnic",
    size: "S",
    sizeCategory: "S",
    sleeveLength: "short",
    dressLength: "mini",
    material: "brocade",
    garmentMeasurements: { bust: 84, waist: 68, hips: 92, length: 96 },
    owner: "Mei",
  },
  {
    id: "scarlet-qipao",
    title: "Scarlet qipao",
    dailyPrice: 36,
    fabric: "brocade",
    sensitive: false,
    occasion: true,
    occasionType: "ethnic",
    ethnicStyle: "chinese",
    condition: "brand-new",
    fit: "Classic fitted",
    description: "Traditional red qipao with a fitted festive silhouette and subtle floral detailing.",
    palette: ["#ead7d2", "#c48f88", "#8f5b55"],
    image: cnyTwo,
    preGeneratedTryOnImage: mainInCnyTwo,
    preGeneratedTryOnVideo: mainInCnyTwoVideo,
    category: "Ethnic",
    size: "S",
    sizeCategory: "S",
    sleeveLength: "short",
    dressLength: "mini",
    material: "brocade",
    garmentMeasurements: { bust: 84, waist: 68, hips: 92, length: 98 },
    owner: "Lin",
  },
  {
    id: "rose-anarkali",
    title: "Rose anarkali",
    dailyPrice: 32,
    fabric: "chiffon",
    sensitive: true,
    occasion: true,
    occasionType: "ethnic",
    ethnicStyle: "indian",
    condition: "worn-few",
    fit: "Flowy festive",
    description: "Soft anarkali silhouette with easy movement and a lined bodice suited for long celebrations.",
    palette: ["#f0dfd8", "#c7a59c", "#9a756e"],
    image: dressTwo,
    category: "Ethnic",
    size: "M",
    sizeCategory: "M",
    sleeveLength: "long",
    dressLength: "maxi",
    material: "chiffon",
    garmentMeasurements: { bust: 96, waist: 80, hips: 108, length: 140 },
    owner: "Priya",
  },
  {
    id: "festive-saree-set",
    title: "Festive saree set",
    dailyPrice: 28,
    fabric: "lace",
    sensitive: false,
    occasion: true,
    occasionType: "ethnic",
    ethnicStyle: "indian",
    condition: "well-used",
    fit: "Festive drape",
    description: "Traditional Indian saree-inspired festive set with a rich drape and statement border.",
    palette: ["#efe3da", "#d0b9ad", "#9f8478"],
    image: indianSaree,
    preGeneratedTryOnImage: mainInIndianSaree,
    preGeneratedTryOnVideo: mainInIndianSareeVideo,
    category: "Ethnic",
    size: "S",
    sizeCategory: "S",
    sleeveLength: "short",
    dressLength: "maxi",
    material: "lace",
    garmentMeasurements: { bust: 86, waist: 70, hips: 96, length: 145 },
    owner: "Asha",
  },
  {
    id: "campus-knit-dress",
    title: "Campus knit dress",
    dailyPrice: 14,
    fabric: "knit",
    sensitive: true,
    occasion: false,
    occasionType: "university",
    ethnicStyle: "",
    condition: "worn-few",
    fit: "Easy fitted",
    description: "Comfortable soft-knit dress designed for long campus days and light layering.",
    palette: ["#ece3dc", "#cdbdb3", "#857970"],
    image: dressSix,
    category: "Daily",
    size: "M-L",
    sizeCategory: "M",
    sleeveLength: "long",
    dressLength: "midi",
    material: "knit",
    garmentMeasurements: { bust: 98, waist: 82, hips: 108, length: 116 },
    owner: "Hana",
  },
];

export const eventData = [
  {
    id: "rooftop-dinner",
    date: 24,
    title: "Rooftop Dinner",
    time: "7:30 PM",
    look: "Powder drape set with pearl flats",
    reminder: "Reminder set for 4:00 PM",
  },
  {
    id: "brand-fitting",
    date: 26,
    title: "Brand Fitting",
    time: "11:00 AM",
    look: "Warm grey knit with cream tailoring",
    reminder: "Fabric prep reminder active",
  },
  {
    id: "gallery-opening",
    date: 29,
    title: "Gallery Opening",
    time: "6:00 PM",
    look: "Silk bias dress with muted gold jewelry",
    reminder: "Book shared clutch by Friday",
  },
];

export const tryOnModes = {
  static: {
    title: "Static composition",
    copy: "The silhouette stays structured with a clean waistline and soft drape through the skirt.",
  },
  motion: {
    title: "Motion simulation",
    copy: "The hem opens slightly in motion, and the cupro-silk blend keeps fluid movement around the legs.",
  },
};
